### ISSUE TITLE
Why not use git-remote-url?

### ISSUE THREAD

**Issue by RichardLitt** [sindresorhus/git-remote-origin-url#5]
I'm wondering what the design decisions were for not using [git-remote-url](https://www.npmjs.com/package/git-remote-url).

**Comment by sindresorhus** [comment]
Compare the first commit dates:

- https://github.com/sindresorhus/git-remote-origin-url/commit/ea860a764995dd88b26d068d76fb111a071959a8
- https://github.com/marco-c/git-remote-url/commit/360fd2a37c98df35e4e318c5472cb3af4764177a

**Comment by RichardLitt** [comment]
Thanks.
