### ISSUE TITLE
Make the remote name configurable

### ISSUE THREAD

**Issue by Deuchnord** [sindresorhus/git-remote-origin-url#8]
In some configurations, we can have to work on a fork instead of the original repository. In such situations, the original repository may have another name for more comfort, e.g. `upstream`, `origin` being the remote name for the fork.

Currently, this library doesn't take in account this case. Is it possible to add a new argument to the function exported, so we can tell it which remote name we want the URL from?

**Comment by RichardLitt** [comment]
I don't see why it wouldn't be possible to create a PR for this. But at that point, maybe a more general git-remote-url library would be more useful?

**Comment by Deuchnord** [comment]
> I don't see why it wouldn't be possible to create a PR for this.

I was actually proposing this before opening a PR :)

> But at that point, maybe a more general git-remote-url library would be more useful?

Yes, it would, I was just wondering if it wouldn't benefit more to contribute to this library to before creating yet another one.

**Comment by RichardLitt** [comment]
Yeah! Sweet. I'm just a contributor, but I think this sounds good to me. :)

**Comment by Deuchnord** [comment]
OK, I'll make a PR ASAP, then :)

**Comment by RichardLitt** [comment]
Cool! note - I am not a maintainer!
